# Generated by Django 3.2.5 on 2021-09-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mypost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mypost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MyPost',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
