# Generated by Django 3.2.5 on 2021-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_mycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCategory',
        ),
    ]
