# Generated by Django 3.2.5 on 2021-09-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_update_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
