# Generated by Django 3.2.6 on 2021-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0003_user_calc_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_point',
            field=models.IntegerField(default=0),
        ),
    ]
