# Generated by Django 3.2.6 on 2021-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0004_user_cur_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calc_point',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cur_point',
        ),
    ]
