# Generated by Django 3.2.5 on 2021-09-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0002_user_user_point'),
        ('notice', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.user'),
        ),
    ]
